-- Database: spring_security_jwt

-- DROP DATABASE IF EXISTS spring_security_jwt;

--CREATE DATABASE spring_security_jwt
  --  WITH
    --OWNER = postgres
    --ENCODING = 'UTF8'
    --LC_COLLATE = 'English_United States.1252'
    --LC_CTYPE = 'English_United States.1252'
    --LOCALE_PROVIDER = 'libc'
    --TABLESPACE = pg_default
    --CONNECTION LIMIT = -1
    --IS_TEMPLATE = False;

DROP TABLE IF EXISTS USERS_ROLES;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLES;

CREATE TABLE USERS(
	ID			SERIAL	PRIMARY KEY,
	USERNAME	VARCHAR(250) NOT NULL UNIQUE,
	PASSWORD	VARCHAR(250) NOT NULL
);

CREATE TABLE ROLES(
	ID		SERIAL PRIMARY KEY,
	NAME 	VARCHAR(250) NOT NULL UNIQUE
);

CREATE TABLE USERS_ROLES (
	ID_USERS	INT	NOT NULL REFERENCES USERS (ID),
	ID_ROLES	INT	NOT NULL REFERENCES ROLES (ID),
	PRIMARY KEY (ID_USERS, ID_ROLES)
);

INSERT INTO ROLES (NAME) VALUES 
	('ADMIN'),
	('USER');

SELECT * FROM USERS;
SELECT * FROM ROLES;