spring.application.name=Spring-Security-JWT

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_jwt
spring.datasource.username=postgres
spring.datasource.password=postgres

application.title = Spring-Security-JWT
application.description = Prueba de concepto de Spring Security con JWT
application.version = 1.0.0
