spring.application.name=Spring-Security-JWT
spring.output.ansi.enabled=always

application.title = Spring-Security-JWT
application.description = Spring Security Proof of Concept with JWT
application.version = 1.0.0

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_security_jwt
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa..open-in-view=false
